- hosts: apache-hosts
  tasks:
  - name: update
    apt: update_cache=yes
    sudo: yes
    
  - name: install apache2
    apt: name=apache2 state=present
    sudo: yes
  - name: restart apache2
    service: name=apache2 state=restarted
    sudo: yes
  - debug: msg="apache has been installed"